### ISSUE TITLE
Widget should have a transparent background and enable forcing the light/dark theme

### ISSUE THREAD

**Issue by wraitii** [argentlabs/dappland#108]
^ Title.

The widget does not have a transparent background, which makes iFrame integration tricky.
Furthermore, the theme (dark/light) changes with the system settings, and the iFrame integrator should be able to force it.

**Comment by graemeblackwood** [comment]
@wraitii Can you share more about what you want to achieve with transparency? Generally these kinds of widgets are quite fixed in their appearance, but I accept that if we offer light / dark mode, that bit should have some control.

**Comment by graemeblackwood** [comment]
@wraitii Just added a theme parameter to the widget:

https://www.dappland.com/widgets/rating?dappname=briq&theme=dark
https://www.dappland.com/widgets/rating?dappname=briq&theme=light
